# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 7612a5300491edda7cfb0e93f39ea947407bdd52135064a189151d12aa2111a7eb0090d16f86201c74d32e5a2e57bb065b82afc848c5a60f5c834c6635026bb0

test:
  domain_name: example.com 
  secret_key_base: 61fbc6e86017e249973e358eb8945846818879947c5443257048504730535dc912615c7ff1a5cad9fa61e5aee7e12d546d3cde747d061c1377d7fe2a613ff4f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
